/**
 * Browser-side web-push helpers.
 *
 * The service worker is generated by vite-plugin-pwa (with our push handlers
 * inlined via workbox.importScripts), so we simply reuse `ready` here.
 */

export type PushSubscribeResult =
  | { ok: true; endpoint: string; p256dh: string; auth: string }
  | { ok: false; reason: "unsupported" | "denied" | "no-sw" | "error"; message?: string };

function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const raw = atob(base64);
  const output = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) output[i] = raw.charCodeAt(i);
  return output;
}

export function pushSupported(): boolean {
  return (
    typeof window !== "undefined" &&
    "serviceWorker" in navigator &&
    "PushManager" in window &&
    "Notification" in window
  );
}

export function notificationPermission(): NotificationPermission | "unsupported" {
  if (!pushSupported()) return "unsupported";
  return Notification.permission;
}

/**
 * Subscribe this browser to web push. Reuses an existing subscription when
 * present so we do not pile up duplicate endpoints.
 */
export async function ensurePushSubscription(vapidPublicKey: string): Promise<PushSubscribeResult> {
  if (!pushSupported()) return { ok: false, reason: "unsupported" };
  if (Notification.permission === "denied") return { ok: false, reason: "denied" };

  try {
    const registration = await navigator.serviceWorker.ready;
    if (!registration.pushManager) return { ok: false, reason: "unsupported" };

    const existing = await registration.pushManager.getSubscription();
    const subscription =
      existing ??
      (await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(vapidPublicKey) as BufferSource,
      }));

    const json = subscription.toJSON();
    const endpoint = json.endpoint;
    const p256dh = json.keys?.p256dh;
    const auth = json.keys?.auth;
    if (!endpoint || !p256dh || !auth) {
      return { ok: false, reason: "error", message: "Subscription payload incomplete" };
    }
    return { ok: true, endpoint, p256dh, auth };
  } catch (err) {
    return { ok: false, reason: "error", message: String(err).slice(0, 200) };
  }
}
